name: random-graphs
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python
  - arm_pyart
  - act-atmos
  - matplotlib
  - hvplot
  - ipython
  - notebook
  - jupyterlab
  - holoviews
  - geoviews
  - cartopy
  - numpy
  - dask
  - dask-labextension
  - distributed
  - xarray
  - xradar
  - pandas>=1.3.4
  - datashader
  - geopandas
  - xmovie
  - fiona
  - ffmpeg
  - networkx>=2.6.3
  - plotly
  - satpy
  - metpy
  - pip
  - pip:
    - pydot
    - schemdraw
